/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_squareup_tape_QueueFileNative */

#ifndef _Included_com_squareup_tape_QueueFileNative
#define _Included_com_squareup_tape_QueueFileNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_squareup_tape_QueueFileNative_nativeNew
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    getFileLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_squareup_tape_QueueFileNative_getFileLength
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    add
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_add___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    add
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_add___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_squareup_tape_QueueFileNative_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    peek
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_squareup_tape_QueueFileNative_peek__
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    peek
 * Signature: (Lcom/squareup/tape/QueueFile/ElementReader;)V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_peek__Lcom_squareup_tape_QueueFile_ElementReader_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    forEach
 * Signature: (Lcom/squareup/tape/QueueFile/ElementReader;)V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_forEach
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_squareup_tape_QueueFileNative_size
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    remove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_remove
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_squareup_tape_QueueFileNative_close
  (JNIEnv *, jobject);

/*
 * Class:     com_squareup_tape_QueueFileNative
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_squareup_tape_QueueFileNative_toString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
